apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alert_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api'
        static_configs:
          - targets: ['api-service:5000']
        metrics_path: '/metrics'
        scrape_interval: 10s

      # Remover frontend hasta que tenga métricas
      # - job_name: 'frontend'
      #   static_configs:
      #     - targets: ['frontend-service:80']
      #   metrics_path: '/metrics'
      #   scrape_interval: 10s

      # Remover MongoDB hasta configurar exporter
      # - job_name: 'mongodb'
      #   static_configs:
      #     - targets: ['mongo-service:27017']

      # Simplificar kubernetes discovery por ahora
      # - job_name: 'kubernetes-pods'
      #   kubernetes_sd_configs:
      #     - role: pod
      #   relabel_configs:
      #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      #       action: keep
      #       regex: true

  alert_rules.yml: |
    groups:
      - name: task-manager-alerts
        rules:
          - alert: HighResponseTime
            expr: http_request_duration_seconds > 0.5
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High response time detected"
              description: "Response time is above 500ms for 2 minutes"

          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "High error rate detected"
              description: "Error rate is above 10% for 2 minutes"