apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /opt/keycloak/data && chmod -R 775 /opt/keycloak/data"]
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
        securityContext:
          runAsUser: 0
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0
        args:
          - start-dev
          - --import-realm
          - --hostname=keycloak.local  # AGREGAR ESTA LÍNEA
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin123"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc