apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded MongoDB URL
  MONGO_URL: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvLXNlcnZpY2U6MjcwMTcvdGFza21hbmFnZXI/YXV0aFNvdXJjZT1hZG1pbg==