apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded: admin
  MONGO_ROOT_USERNAME: YWRtaW4=
  # Base64 encoded: password123
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQxMjM=